name: CI

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
      platform: aws
      region: us-east-1
      account: 123456789012

      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: "Display Message"
        run: echo "Hello World"

      - name: "Show env vars"
      # if: ${{env.platform == 'aws'}}
        run: |
          echo "This is the value of platform: ${{env.platform}}"
          echo "This is the value of region: ${{env.region}}"
          echo "This is the value of account: ${{env.account}}"

          echo "This is the username value": ${{env.username}}
          echo "This is the password value": ${{env.password}}
          
      - name: "Showing events"
        run: |
          echo "Event: ${{toJson(github.event)}}"
      
      - uses: actions/checkout@v2  
          
      - name: "Authenticate to GCP"  
        uses: google-github-actions/auth@v2.0.1
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
      
      - name: "Set Up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id:  testing-project-439416

      - name: Copy files to GCS
        run: |
          gsutil -m rsync -c -r -x "gha-creds-[a-z0-9]+\.json" ./ gs://github-actions-gcs-1/
           